### ISSUE TITLE
Context menu logo (Enhancement)

### ISSUE THREAD

**Issue by gabxln** [ip7z/7zip#17]
Could you put the program logo in the context menu?

![Captura de tela 2024-03-14 132025](https://github.com/ip7z/7zip/assets/107080676/be02e8f8-1889-4a6a-8120-f25fe3319890)

**Comment by Florin9doi** [comment]
![image](https://github.com/ip7z/7zip/assets/2995486/4f727f0c-d5e5-4c93-b331-cd63aa55d0c2)
