### ISSUE TITLE
Certain video formats are being treated as an archive in the context menu

### ISSUE THREAD

**Issue by raziel711** [ip7z/7zip#23]
System information:
OS: Windows 10 22H2
7-Zip version: 24.04 beta x64

I am having as issue where 7-Zip's context menu shows the options to extract files for mkv and webm video files.  

I have the following context menu items selected in the options menu:
- Extract Here
- Extract to Folder
- Add to archive...
- 7-Zip > CRC SHA >

When I right click on most video files, only the add to archive and CRC entries appear, which is what I would expect; however, when I right click on any mkv or webm files I get the following:

![Untitled](https://github.com/ip7z/7zip/assets/75226602/3bcfbdb3-078c-4a71-998b-c2c4c25bb904)

It seems like 7-Zip is treating these formats as an archive.  Would it be possible to prevent the extraction options from showing up in the context menu for all media files?

**Comment by ip7z** [comment]
There is "exclude list" for file extensions in 7-Zip.
I'll update that list for `mkv` and `webm`.

**Comment by raziel711** [comment]
7-Zip 24.05 has fixed this issue for me.  Thanks.

**Comment by raziel711** [comment]
7-Zip 24.05 has fixed this issue for me.  Thanks.
