### ISSUE TITLE
[Feature Request] Teledisk image (.td0) extraction support

### ISSUE THREAD

**Issue by MasterDumblord** [ip7z/7zip#44]
Hello. I have downloaded an old version of Windows 1.03 from Winworld for the HP 150 x86 based PC, and the disk images are all Teledisk image format (.td0). I do not have the ability to use Teledisk, as it is a DOS program, and I am running 64-bit Windows 7. Can you add Teledisk extraction support, as all the software I have for disk images, including 7-Zip cannot open them. Thanks in advance!

**Comment by ip7z** [comment]
I suppose most users don't need support for that format.
So now we don't want additional code complexity in 7-Zip related to such rare cases.

**Comment by MasterDumblord** [comment]
Well dang. I wish there was a solution to this. Thanks anyway.
