### ISSUE TITLE
[Request] Context menu - unzip in different folder

### ISSUE THREAD

**Issue by milen-prg** [ip7z/7zip#51]
The winrar (?) had option if are selected several archives, and with right mouse button has menu - unzip each in different folder, where name of the folder is the name of the archive.
This is very convenient.

**Comment by BiatuAutMiahn** [comment]
Afaik you can already do this by selecting archives, right-click drag and drop, upon mouse up context menu appears goto 7-zip > Extract *\

**Comment by milen-prg** [comment]
> Afaik you can already do this by selecting archives, right-click drag and drop to target folder, upon mouse up context menu appears goto 7-zip > Extract *\

Oh, yes, THIS IS! I didn't understood. Thanks!
