### ISSUE TITLE
Strange result on virustotal.com - malicious objects?

### ISSUE THREAD

**Issue by ayv19** [ip7z/7zip#71]
I checked the "https://github.com/ip7z/7zip/releases/download/24.09/7z2409-linux-x64.tar.xz" file on the website virustotal.com. The result shows the presence of malicious text and code. The same result is obtained for the file version 24.08. Version 24.07 is clear. The "https://7-zip.org/a/7z2409-linux-x64.tar.xz" file also suspicious. If I extract the tar file from the xz archive, no malicious objects are detected. What is the reason for this reaction of the site virustotal.com on versions 24.09 and 24.08?

**Comment by ip7z** [comment]
can't repro
