### ISSUE TITLE
关于国内一个公司封装软件收费问题

### ISSUE THREAD

**Issue by zt1115798334** [ip7z/7zip#8]
众里寻她文化传媒（武汉）有限公司汉川分公司 存在封装收费7z软件得情况，咨询一下是否给该公司授权了？这是该公司得7z下载网址 https://7zip.whswxkj.com/index.html  
![屏幕截图 2024-01-16 110420](https://github.com/ip7z/7zip/assets/26216996/3869c209-e58d-4b1b-a2c2-3fe4a6919a79)
![屏幕截图 2024-01-16 110444](https://github.com/ip7z/7zip/assets/26216996/59a2ac87-2b72-4f3b-8839-b1d420824058)
![屏幕截图 2024-01-16 110532](https://github.com/ip7z/7zip/assets/26216996/007912a1-21fc-476c-8847-fb5ac534b94b)

**Comment by 6uO** [comment]
这种公司网站我一般不看直接JMeter伺候
curl -k https://s7zapp.whrszx.com/v3/feedback/add -dcontent=[此处省略万字流言蛮语]
接口失效记得踢踢我
---
Fuck pirated 7-Zip,Install once and charge ￥24.99
Directly dry flip it:
curl -k https://s7zapp.whrszx.com/v3/feedback/add -dcontent=FuckFuckFuck...
